/*changing the headings according to genres*/
function genre1(){
	document.getElementById("headO").innerHTML="Pop"
	document.getElementById("headT").innerHTML=""
	document.getElementById("a1").src="images/albumthumb/pop/pop1.jpg"
	document.getElementById("an1").innerHTML="Camila"
	document.getElementById("a2").src="images/albumthumb/pop/pop2.jpg"
	document.getElementById("an2").innerHTML="reputation"
	document.getElementById("a3").src="images/albumthumb/pop/pop3.jpg"
	document.getElementById("an3").innerHTML="Dua Lipa"
	document.getElementById("a4").src="images/albumthumb/pop/pop4.jpg"
	document.getElementById("an4").innerHTML="Melodrama"
	document.getElementById("a5").src="images/albumthumb/pop/pop5.jpg"
	document.getElementById("an5").innerHTML="Sweetener"
	document.getElementById("a6").src="images/albumthumb/pop/pop6.jpg"
	document.getElementById("an6").innerHTML="Joanne"
	document.getElementById("a7").src="images/albumthumb/pop/pop7.jpg"
	document.getElementById("an7").innerHTML="Lust for Life"
	document.getElementById("a8").src="images/albumthumb/pop/pop8.jpg"
	document.getElementById("an8").innerHTML="Caution"
	
}
function genre2(){
	document.getElementById("headO").innerHTML="Electronic"
	document.getElementById("headT").innerHTML=""
	document.getElementById("a1").src="images/albumthumb/electronic/e1.jpg"
	document.getElementById("an1").innerHTML="See You"
	document.getElementById("a2").src="images/albumthumb/electronic/e2.jpg"
	document.getElementById("an2").innerHTML="Safe in the Hands of Love"
	document.getElementById("a3").src="images/albumthumb/electronic/e3.jpg"
	document.getElementById("an3").innerHTML="AZD"
	document.getElementById("a4").src="images/albumthumb/electronic/e4.jpg"
	document.getElementById("an4").innerHTML="Black Origami"
	document.getElementById("a5").src="images/albumthumb/electronic/e5.jpg"
	document.getElementById("an5").innerHTML="Singularity"
	document.getElementById("a6").src="images/albumthumb/electronic/e6.jpg"
	document.getElementById("an6").innerHTML="Cloud Nine"
	document.getElementById("a7").src="images/albumthumb/electronic/e7.jpg"
	document.getElementById("an7").innerHTML="Oh No"
	document.getElementById("a8").src="images/albumthumb/electronic/e8.jpg"
	document.getElementById("an8").innerHTML="Love Streams"
}
function genre3(){
	document.getElementById("headO").innerHTML="Rock"
	document.getElementById("headT").innerHTML=""
	document.getElementById("a1").src="images/albumthumb/rock/r1.jpg"
	document.getElementById("an1").innerHTML="Night Visions"
	document.getElementById("a2").src="images/albumthumb/rock/r2.jpg"
	document.getElementById("an2").innerHTML="London Calling"
	document.getElementById("a3").src="images/albumthumb/rock/r3.jpg"
	document.getElementById("an3").innerHTML="Crack The Sky"
	document.getElementById("a4").src="images/albumthumb/rock/r4.jpg"
	document.getElementById("an4").innerHTML="American Idiot"
	document.getElementById("a5").src="images/albumthumb/rock/r5.jpg"
	document.getElementById("an5").innerHTML="Riot!"
	document.getElementById("a6").src="images/albumthumb/rock/r6.jpg"
	document.getElementById("an6").innerHTML="Ocean"
	document.getElementById("a7").src="images/albumthumb/rock/r7.jpg"
	document.getElementById("an7").innerHTML="The Dark Side of the Moon"
	document.getElementById("a8").src="images/albumthumb/rock/r8.jpg"
	document.getElementById("an8").innerHTML="As You Were"
}
function genre4(){
	document.getElementById("headO").innerHTML="Jazz"
	document.getElementById("headT").innerHTML=""
	document.getElementById("a1").src="images/albumthumb/jazz/jaz1.jpg"
	document.getElementById("an1").innerHTML="The Boop-A-Doo"
	document.getElementById("a2").src="images/albumthumb/jazz/jaz2.jpg"
	document.getElementById("an2").innerHTML="Beyond Now"
	document.getElementById("a3").src="images/albumthumb/jazz/jaz3.jpg"
	document.getElementById("an3").innerHTML="Coming Forth by Day"
	document.getElementById("a4").src="images/albumthumb/jazz/jaz4.jpg"
	document.getElementById("an4").innerHTML="Towards Language"
	document.getElementById("a5").src="images/albumthumb/jazz/jaz5.jpg"
	document.getElementById("an5").innerHTML="Kin"
	document.getElementById("a6").src="images/albumthumb/jazz/jaz6.jpg"
	document.getElementById("an6").innerHTML="Still Dreaming"
	document.getElementById("a7").src="images/albumthumb/jazz/jaz7.jpg"
	document.getElementById("an7").innerHTML="Day Breaks"
	document.getElementById("a8").src="images/albumthumb/jazz/jaz8.jpg"
	document.getElementById("an8").innerHTML="Emanon"
}
function genre5(){
	document.getElementById("headO").innerHTML="Classical"
	document.getElementById("headT").innerHTML=""
	document.getElementById("a1").src="images/albumthumb/classic/cla1.jpg"
	document.getElementById("an1").innerHTML="Dark Matter"
	document.getElementById("a2").src="images/albumthumb/classic/cla2.jpg"
	document.getElementById("an2").innerHTML="Eon"
	document.getElementById("a3").src="images/albumthumb/classic/cla3.jpg"
	document.getElementById("an3").innerHTML="Dúo del Mar"
	document.getElementById("a4").src="images/albumthumb/classic/cla4.jpg"
	document.getElementById("an4").innerHTML="Removed"
	document.getElementById("a5").src="images/albumthumb/classic/cla5.jpg"
	document.getElementById("an5").innerHTML="The Pearls of Polish"
	document.getElementById("a6").src="images/albumthumb/classic/cla6.jpg"
	document.getElementById("an6").innerHTML="Seven Stars"
	document.getElementById("a7").src="images/albumthumb/classic/cla7.jpg"
	document.getElementById("an7").innerHTML="Without Sinking"
	document.getElementById("a8").src="images/albumthumb/classic/cla8.jpg"
	document.getElementById("an8").innerHTML="Cloître"
}
function genre6(){
	document.getElementById("headO").innerHTML="Techno"
	document.getElementById("headT").innerHTML=""
		document.getElementById("a1").src="images/albumthumb/pop/pop1.jpg"
	document.getElementById("an1").innerHTML="Camila"
}
function genre7(){
	document.getElementById("headO").innerHTML="Country"
	document.getElementById("headT").innerHTML=""
		document.getElementById("a1").src="images/albumthumb/pop/pop1.jpg"
	document.getElementById("an1").innerHTML="Camila"
}
function genre8(){
	document.getElementById("headO").innerHTML="Reggae"
	document.getElementById("headT").innerHTML=""
		document.getElementById("a1").src="images/albumthumb/pop/pop1.jpg"
	document.getElementById("an1").innerHTML="Camila"
}